apiVersion: v1
kind: Service
metadata:
  name: pyre-promotion-service
  namespace: dev
spec:
  selector:
    app: pyre-promotion-pod
  ports:
    - protocol: TCP
      port: 80 # Service port
      targetPort: 8000 # Pod container port
  type: LoadBalancer