name: pyre-promotion CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Install kubectl
        env: 
          HEHE: ${{ vars.KUBE }}
        run: |
          sudo apt-get update && sudo apt-get install -y kubectl
          mkdir -p $HOME/.kube
          echo "$HEHE" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          sudo kubectl get nodes
          
  
      
            
          
