name: pyre-promotion CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: set up kube config
        run: |
          echo ${{ secrets.KUBE_CONFIG }}
          cat ${{ secrets.KUBE_CONFIG }}
          
