name: pyre-promotion CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install kubectl
        env: 
          HEHE: ${{ vars.KUBE }}
        run: |
          sudo apt-get update && sudo apt-get install -y kubectl
          export KUBECONFIG="$HEHE"
          echo 'export KUBECONFIG="$HEHE"' >> .bashrc
          sudo kubectl get nodes
          
  
      
            
          
