name: pyre-promotion CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: create .env file
        run: echo "${{ secrets.ENV_CONTENT }}" > .env

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USER }}/pyre-promotion:latest



  deploy:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.31.1

      - name: set up kube config
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      - name: deploy new image to kubernetes
        run: |
          kubectl set image deployment/pyre-promotion pyre-promotion=${{ secrets.DOCKER_USER }}/pyre-promotion:latest