name: pyre-promotion CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: set up kube config
        env: 
          HEHE: ${{ vars.KUBE }} 
        run: |
          echo "this is my $HEHE"
          
          
