name: pyre-promotion CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: create .env file
        run: echo "${{ secrets.ENV_CONTENT }}" > .env

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USER }}/pyre-promotion:latest



  deploy:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: set up kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: set up kube config
        env: 
          HEHE: ${{ vars.KUBE }} 
        run: |
          cat ${{ env.KUBE }}
          mkdir -p $HOME/.kube
          echo "$HEHE" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          echo "Kube config contents: $HEHE"

      - name: set kube context
        run: |
          kubectl config use-context kubernetes-admin@kubernetes

      - name: deploy new image to kubernetes
        run: |
          kubectl get deployment
          
          
